### Tensor
Tensor is a fundamental data structure in PyTorch, essentially a multi-dimensional array. It can be a scalar, a 1D array (vector), a 2D array (matrix), or a higher-dimensional array. Tensors are similar to NumPy ndarrays, but with the added benefit of GPU acceleration. Their API closely resembles NumPy and MATLAB. Let's walk through some examples of basic tensor operations.

In [2]:
import torch as t

print("PyTorch version: ", t.__version__)

PyTorch version:  2.10.0+cu126


If you have an NVIDIA GPU, you can leverage CUDA (Compute Unified Device Architecture) to accelerate training on the graphics card.

In [3]:
cuda_available = t.cuda.is_available()

print(f"CUDA availability status: {cuda_available}")
print(f"CUDA version: {t.version.cuda}")

CUDA availability status: True
CUDA version: 12.6


In [4]:
if cuda_available:
    print(f"Current graphics card: {t.cuda.get_device_name(0)}")
    
    x = t.rand(5, 3).cuda()

    
    print("Successfully created a tensor on the GPU:")
    print(x)
    
else:
    print("No GPU detected. Please check your installation steps.")

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# x = torch.rand(5, 3).to(device)

Current graphics card: NVIDIA GeForce RTX 3080 Ti
Successfully created a tensor on the GPU:
tensor([[0.1392, 0.8222, 0.1110],
        [0.8507, 0.7996, 0.5010],
        [0.6432, 0.5504, 0.1326],
        [0.7148, 0.7129, 0.5730],
        [0.6753, 0.0660, 0.4449]], device='cuda:0')


In [5]:
# Construct a 5x3 matrix with allocated memory but uninitialized values
x = t.Tensor(5, 3)

x = t.Tensor([[1,2],[3,4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [6]:
# Initialize a 2D array with random values from a uniform distribution over [0, 1]
x = t.rand(5,3)
print(x)

# Initialize a 2D array with random values from a standard normal distribution
y = t.randn(5,3)
print(y)

tensor([[0.0305, 0.2764, 0.1502],
        [0.1089, 0.0517, 0.6004],
        [0.0699, 0.6426, 0.5833],
        [0.4802, 0.1414, 0.0211],
        [0.3958, 0.5686, 0.6318]])
tensor([[-0.7974,  0.9479, -0.5779],
        [ 1.6610, -0.4859,  1.4128],
        [ 0.6821,  0.1453,  0.0303],
        [-1.5742, -0.8310,  0.0648],
        [-0.5119, -0.3544,  1.2508]])


In [7]:
print(x.size()) # Check the shape of x
print(x.size()[1]) # Get the number of columns — two equivalent ways
print(x.size(1))

torch.Size([5, 3])
3
3


In [8]:
x + y # Addition: method 1

tensor([[-0.7669,  1.2243, -0.4277],
        [ 1.7699, -0.4341,  2.0132],
        [ 0.7520,  0.7879,  0.6136],
        [-1.0939, -0.6896,  0.0859],
        [-0.1160,  0.2142,  1.8827]])

In [9]:
t.add(x, y) # Addition: method 2

tensor([[-0.7669,  1.2243, -0.4277],
        [ 1.7699, -0.4341,  2.0132],
        [ 0.7520,  0.7879,  0.6136],
        [-1.0939, -0.6896,  0.0859],
        [-0.1160,  0.2142,  1.8827]])

In [10]:
# Addition: method 3
result = t.Tensor(5, 3) # Pre-allocate memory
t.add(x, y, out=result) # Output the result
result

tensor([[-0.7669,  1.2243, -0.4277],
        [ 1.7699, -0.4341,  2.0132],
        [ 0.7520,  0.7879,  0.6136],
        [-1.0939, -0.6896,  0.0859],
        [-0.1160,  0.2142,  1.8827]])

In [11]:
print('Initial y')
print(y)

print('After add(), y is:')
y.add(x)  # Regular addition, y remains unchanged
print(y)

print('After add_(), y is:')
y.add_(x)  # In-place addition, y is modified
print(y)

Initial y
tensor([[-0.7974,  0.9479, -0.5779],
        [ 1.6610, -0.4859,  1.4128],
        [ 0.6821,  0.1453,  0.0303],
        [-1.5742, -0.8310,  0.0648],
        [-0.5119, -0.3544,  1.2508]])
After add(), y is:
tensor([[-0.7974,  0.9479, -0.5779],
        [ 1.6610, -0.4859,  1.4128],
        [ 0.6821,  0.1453,  0.0303],
        [-1.5742, -0.8310,  0.0648],
        [-0.5119, -0.3544,  1.2508]])
After add_(), y is:
tensor([[-0.7669,  1.2243, -0.4277],
        [ 1.7699, -0.4341,  2.0132],
        [ 0.7520,  0.7879,  0.6136],
        [-1.0939, -0.6896,  0.0859],
        [-0.1160,  0.2142,  1.8827]])


In [12]:
print(x[:, 1]) # torch.Size([5])     — 1D
print(x[:, 1:2]) # torch.Size([5, 1])  — 2D

tensor([0.2764, 0.0517, 0.6426, 0.1414, 0.5686])
tensor([[0.2764],
        [0.0517],
        [0.6426],
        [0.1414],
        [0.5686]])


Tensors support a wide range of operations, including mathematical computations, linear algebra, indexing, and slicing, with an API very similar to NumPy.

Converting between Tensors and NumPy arrays is seamless and efficient. For operations not directly supported by Tensors, you can convert to a NumPy array, perform the operation, and convert back.

In [13]:
a = t.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [14]:
b = a.numpy() # Tensor -> Numpy
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [15]:
import numpy as np
a = np.zeros(5)
b = t.from_numpy(a) # Numpy -> Tensor
print(a)
print(b)

[0. 0. 0. 0. 0.]
tensor([0., 0., 0., 0., 0.], dtype=torch.float64)


Tensors and NumPy arrays share the same underlying memory, so conversion between them is fast and virtually cost-free. However, this also means that modifying one will affect the other.

In [16]:
b.add_(1)  # Functions ending with `_` modify the tensor in-place
print(a)
print(b)  # Tensor and NumPy array share the same memory

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [17]:
scalar_b0 = b[0]
scalar_b0

tensor(1., dtype=torch.float64)

In [18]:
scalar_b0.size() # 0-dim tensor

torch.Size([])

In [19]:
# .item() works on any tensor with a single element, regardless of its dimensions. It will raise an error if the tensor contains more than one element
scalar_b0.item()

1.0

In [20]:
tensor_1 =  t.tensor([1]) # tensor_1 is 1-dimensional, scalar_b0 is 0-dimensional
tensor_1, scalar_b0

(tensor([1]), tensor(1., dtype=torch.float64))

In [21]:
tensor_1.size(), scalar_b0.size()

(torch.Size([1]), torch.Size([]))

In [22]:
tensor_1.item()

1

Additionally, PyTorch provides `torch.tensor`, an interface very similar to `np.array`. The two are used in much the same way. Note the distinction from `torch.Tensor`, which is a class.

In [23]:
tensor = t.tensor([3,4]) # Create a new tensor containing the elements 3 and 4
tensor

tensor([3, 4])

In [24]:
scalar = t.tensor(3)
scalar

tensor(3)

In [25]:
old_tensor = tensor
new_tensor = old_tensor.clone()
new_tensor[0] = 1111
old_tensor, new_tensor

(tensor([3, 4]), tensor([1111,    4]))

Note that `t.tensor()` and `tensor.clone()` always copy the data, so the new tensor no longer shares memory with the original. If you want to share memory, use `torch.from_numpy()` or `tensor.detach()` instead — both create a new tensor that shares the underlying memory.

`.detach()` separates a tensor from the computation graph and returns a new tensor that shares the same underlying memory but no longer participates in gradient computation.

In [26]:
new_tensor = old_tensor.detach()
new_tensor[0] = 1111
old_tensor, new_tensor

(tensor([1111,    4]), tensor([1111,    4]))

A Tensor can be moved to the GPU using the `.cuda()` method to take advantage of GPU-accelerated computation.

In [28]:
# On machines without CUDA support, the next step will still run on the CPU
# You only need to specify the device index when you have multiple GPUs — for example, "cuda:1" refers to the second GPU. With a single GPU, "cuda" and "cuda:0" are equivalent.
device = t.device("cuda" if t.cuda.is_available() else "cpu")

x = x.to(device)
y = y.to(x.device)
z = x @ y.T
z

tensor([[ 0.2507,  0.2365,  0.3329, -0.2111,  0.3385],
        [-0.2769,  1.3789,  0.4910, -0.1032,  1.1288],
        [ 0.4836,  1.0189,  0.9167, -0.4694,  1.2277],
        [-0.2041,  0.8310,  0.4855, -0.6211,  0.0142],
        [ 0.1224,  1.7256,  1.1333, -0.7709,  1.2654]], device='cuda:0')

Additionally, you can use `tensor.cuda()` to copy a tensor to the GPU, but this approach is not recommended.

Transferring data from system memory to GPU memory incurs additional overhead. The advantages of GPU computation only become apparent with large-scale data and complex operations.